### PR TITLE
feat: updated module

### PR DESCRIPTION
**Pull request by AshutoshAM2002**
## what
* Updated module

### CODE REVIEW

**Comment by nileshgadgi** [comment]
@AshutoshAM2002 security checks are failing, please take a look!

**Review by vaibhav7797 — APPROVED** [review]
LGTM!

**Comment by nileshgadgi** [comment]
Did you tested the module? creation and destruction both?

**Comment by AshutoshAM2002** [comment]
> Did you tested the module? creation and destruction both?

Yes tested both creation and destruction

**Comment by AshutoshAM2002** [comment]
> @AshutoshAM2002 security checks are failing, please take a look!

They are the security checks, getting in defsec but tfsec in good so we can skip it, I already talked about the same with Anmol sir

**Review by nileshgadgi — APPROVED** [review]
LGTM!

**Review by VishwajitNagulkar — APPROVED** [review]

**Pull request merged**
